# Generated by Django 6.1.1 on 2026-09-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0002_alter_contact_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name']},
        ),
    ]
