# Generated by Django 6.1.1 on 2026-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0003_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
