# Generated by Django 6.1.1 on 2026-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0004_contact_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
